<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Halaga - Parokya ni Edgar</title>
</head>
<body>
    <h1>Song - Halaga - Parokya ni Edgar</h1>
    
    <h2>Lyrics:</h2>
    <?php
    echo "<pre>";
    echo "[Intro]\n";
    echo "D - A - Bm - A - D - A - Bm - A - D\n\n";

    echo "[Verse 1]\n";
    echo "       D\n";
    echo "Umiiyak ka na naman\n";
    echo "                     A\n";
    echo "Langya talaga, wala ka bang ibang alam\n";
    echo "      Bm\n";
    echo "Namumugtong mga mata\n";
    echo "          A\n";
    echo "Kailan pa ba kaya ikaw magsasawa\n\n";

    echo "[Refrain]\n";
    echo "          G+       D             A\n";
    echo "Sa problema na iyong pinapasan\n";
    echo "           G+                      D                 Bm            A\n";
    echo "Hatid sayo ng boyfriend mong hindi mo maintindihan\n\n";

    echo "[Verse 2]\n";
    echo "       D\n";
    echo "May kwento kang pandrama na naman\n";
    echo "                     A\n";
    echo "Parang pang TV na walang katapusan\n";
    echo "      Bm\n";
    echo "Hanggang kailan ka bang ganyan\n";
    echo "          A\n";
    echo "Hindi mo ba alam na walang pupuntahan\n\n";

    echo "[Pre-Chorus]\n";
    echo "          G+            D                    A\n";
    echo "Ang pagtiyaga mo dyan sa boyfriend mong tanga\n";
    echo "           G+                 D               Bm              A\n";
    echo "Na wala nang ginagawa kundi ang paluhain ka\n\n";

    echo "[Chorus]\n";
    echo "       D               G+           Bm                 A\n";
    echo "Sa libu-libong pagkakataon na tayo'y nagkasama\n";
    echo "       D               G+            Bm             A\n";
    echo "Ilang ulit palang kitang nakitang masaya\n";
    echo "       D                G+              Bm\n";
    echo "Naiinis akong isipin na ginaganyan ka nya\n";
    echo "           A                D\n";
    echo "Siguro ay hindi niya lang alam ang iyong tunay na halaga\n\n";

    echo "[Verse 3]\n";
    echo "       D\n";
    echo "Hindi na dapat pag-usapan pa\n";
    echo "                     A\n";
    echo "Nagpapagod na rin ako sa aking kakasalita\n";
    echo "      Bm\n";
    echo "Hindi ka rin naman nakikinig\n";
    echo "          A\n";
    echo "Kahit sobrang pagod na ang aking bibig\n";
    echo "           G+           D              A\n";
    echo "Sa mga payo kong di mo pinapansin\n";
    echo "       G+            D              Bm              A\n";
    echo "Akala mo'y nakikinig di rin naman tatanggapin\n";
        
       //continue echoing the ramaining verses, chroruses, bridge, and outro...

    echo "</pre>";
    ?>
</body>
</html>