<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="csstyle.css"> <!-- Assuming the CSS file is named "csstyle.css" -->
    <title>You'll Be Safe Here</title>
</head>
<body>
    <h1>Song - A Year Ago</h1>

    <h2>Lyrics:</h2>
    <?php
        echo "<n>[Verse 1]</n>";
        echo "<n>G</n>";
        echo "<n>I miss you</n>";
        echo "<n>I miss you</n>";
        echo "<n>I miss you</n>";
        echo "<n>I miss you</n>";
        echo "<n>Your name's still on my coffee cup</n>";
        echo "<n>Em</n>";
        echo "<n>I miss you</n>";
        echo "<n>The way you chose the films we watched</n>";
        echo "<n>C</n>";
        echo "<n>I miss you, babe</n>";
        echo "<n>D</n>";
        echo "<n>If only I had told you that before</n>";
        echo "<n>G</n>";
        echo "<n>Maybe I would never have to miss you</n>";
        echo "<n>Singing by the kitchen sink</n>";
        echo "<n>Em</n>";
        echo "<n>I miss you</n>";
        echo "<n>Not knowing I was listening</n>";
        echo "<n>C</n>";
        echo "<n>I miss you, babe</n>";
        echo "<n>D</n>";
        echo "<n>You embody everything that I am not</n>";
        echo "<n>And, now, I'm just somebody you forgot</n>";

        echo "<n>[Chorus]</n>";
        echo "<n>G</n>";
        echo "<n>I wish it was a year ago</n>";
        echo "<n>Em</n>";
        echo "<n>I wish that I could hold you close</n>";
        echo "<n>C</n>";
        echo "<n>Now I'm driving past your house, I know</n>";
        echo "<n>D</n>";
        echo "<n>The lights are on, you're not alone</n>";
        echo "<n>G</n>";
        echo "<n>I wonder if you're making eyes</n>";
        echo "<n>Em</n>";
        echo "<n>I wonder if he loves you like</n>";
        echo "<n>C</n>";
        echo "<n>The way you said that only I could do</n>";
        echo "<n>D</n>";
        echo "<n>I wish that I could tell you that I miss you</n>";

    ?>
</body>
</html>

 
