<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="csstyle.css"> <!-- Assuming the CSS file is named "csstyle.css" -->
    <title>You'll Be Safe Here</title>
</head>
<body>
    <h1>Song - Mag-balik</h1>

    <h2>Lyrics:</h2>
    <?php
     
echo "[Intro]"
 
echo "E  B  C#m  A";
echo "E  B  C#m  A":
 
 
echo "[Verse]";
 
echo "E           B              C#m";
echo "Wala na ang dating pagtingin";
echo "Sawa na ba sa'king lambing";
echo "E         B";
echo "Wala ka namang dahilan";
echo "C#m             A";
echo "bakit bigla nalang nangiwan";
 
echo "E           B             C#m";
echo "Hindi na alam ang gagawin";
echo "C#m       A";
echo "Upang ika’y magbalik sakin";
echo "E             B";
echo "Ginawa ko naman ang lahat"; 
echo "C#m           A";
echo "bakit bigla nalang naghanap";
 
 
echo "[Refrain]";
 
echo "F#m        B";
echo "Hindi magbabago";
echo "F#m    B";
echo "Pagmamahal sa iyo";
echo "F#m       B";
echo "Sana’y pakinggan mo";          
 A           B
echo "Ang awit ng pusong ito";     
 
 
echo "[Chorus]";
 
echo "E                   B";
echo "Tulad ng mundong hindi";
echo "      C#m";
echo "Tumitigil sa pag-ikot";
echo "    A";
echo "Pag-ibig di mapapagod";
echo "E                   B";
echo "Tulad ng ilog na hindi";
echo "      C#m";
echo "Tumitigil sa pag agos";
echo "     A";
echo "Pag ibig di matatapos";
 
 
echo "[Instrumental]":
 
echo "E  B  C#m  A";
echo "E  B  C#m  A";
 
 
echo "[Verse]";
 
echo "E           B             C#m";
echo "Alaala’y bumabalik';
echo ""        A";
echo "Mga panahong nasasabik";
echo "E             B";
Echo "Sukdulang mukha ay';
echo "C#m           A";
echo "Laging nasa panaginip";
 
echo "E                B";
echo "Bakit biglang pinagpalit";
echo "C#m            A";
echo "Pagsasamaha'y tila nawaglit";
echo "E            B";
echo "Ang dating walang hanggan";
echo "C#m          A";
echo "Nagkaroon ng katapusan";
 
 
 
echo "[Refrain]";
 
echo "F#m        B";
echo "Hindi magbabago";
echo "F#m    B";
echo "Pagmamahal sa iyo";
echo F#m       B";
echo "Sana’y pakinggan mo ";         
echo " A           B";
echo "Ang awit ng pusong ito   ";   
 
 
echo "[Chorus 2]";
 
echo "E                   B";
echo "Tulad ng mundong hindi!!";
echo "      C#m";
echo "Tumitigil sa pag-ikot";
echo "    A';
echo "Pag-ibig di mapapagod";
echo "E                   B";
echo "Tulad ng ilog na hindi!!";
echo "      C#m";
echo "Tumitigil sa pag agos";
echo "      A";
echo "Pag ibig di matatapos";
 
 
echo "[Instrumental]";
 
echo "(ad libitum)";
 
echo "C#5  Eb5  E  F#  E  Eb";
echo "C#m E  A";
 
 
echo "[Chorus]";
 
echo "E                   B";
echo "Tulad ng mundong hindi";
echo "      C#m";
echo "Tumitigil sa pag-ikot";
echo  " A";
echo "Pag-ibig di mapapagod";
echo "(then pasok!!)";
 
echo "E                   B";
echo "Tulad ng ilog na hindi';
echo  "C#m";
echo "Tumitigil sa pag agos";
echo     " A";
echo "Pag ibig 'di matatapos;"
 
 
echo "[Outro]";
 
echo "E  B  C#m  A";
echo   "tumitigil............(pag-ibig 'di matatapos)";
echo "E  B  C#m  A";
echo "tumitigil............";
echo "A   (let ring)";
echo "pag-ibig di matatapos.....";
    